### ISSUE TITLE
Seomatic Not Found

### ISSUE THREAD

**Issue by darinlarimore** [nystudio107/craft-instantanalytics-ga4#1]
### Describe the bug
```Class "nystudio107\seomatic\Seomatic" not found```
Getting this error traces back to https://github.com/nystudio107/craft-instantanalytics-ga4/blob/develop-v4/src/helpers/Analytics.php#L34-L36

### To reproduce
Steps to reproduce the behaviour:
Install plugin without SEOmatic also installed.

### Expected behaviour
Should gracefully exit

I think maybe adding check for it like this or something could silence it.
```
if (!class_exists(Seomatic::class)) {
     return null;
 }
```

### Screenshots
<img width="559" alt="Screenshot 2023-06-07 at 5 25 01 PM" src="https://github.com/nystudio107/craft-instantanalytics-ga4/assets/20300635/8ae6390c-5c65-4ac5-a81a-fec67b1bb9d4">

<img width="745" alt="Screenshot 2023-06-07 at 5 25 06 PM" src="https://github.com/nystudio107/craft-instantanalytics-ga4/assets/20300635/be7088d2-c6c0-4f9d-8bac-d633221b9626">

### Versions
- Plugin version:
"develop-v4"
- Craft version:
"^4.3",

**Comment by khalwat** [comment]
Good catch, thanks!

**Comment by khalwat** [comment]
Addressed in: [73792e02a03b25d4a370ba83613e613a6f7e2f49](https://github.com/nystudio107/craft-instantanalytics-ga4/commit/73792e02a03b25d4a370ba83613e613a6f7e2f49)
