### ISSUE TITLE
parseEnv() error with Craft 3 version

### ISSUE THREAD

**Issue by bymayo** [nystudio107/craft-instantanalytics-ga4#11]
### Describe the bug

We're getting an error with `parseEnv()` on lines 315 and 316 in `../vendor/nystudio107/craft-instantanalytics-ga4/src/ga4/Analytics.php` using Craft 3.6.18.

Looks like it needs to be Craft::parseEnv not App::parseEnv

### To reproduce
Steps to reproduce the behaviour:
1. Add something to the basket
2. Error appears

### Versions
- Plugin version: 3.0.0-beta.1
- Craft version: 3.6.18

**Comment by khalwat** [comment]
Addressed in 3.0.0-beta.2: https://github.com/nystudio107/craft-instantanalytics-ga4/releases/tag/3.0.0-beta.2
