### ISSUE TITLE
instantAnalytics.setApiSecret('xyz') doesn't update API secret

### ISSUE THREAD

**Issue by mikeymeister** [nystudio107/craft-instantanalytics-ga4#16]
When following the example from the docs below: 
```
{% do instantAnalytics.setMeasurementId("G-7DDE6SKB8E") %}
{% do instantAnalytics.setApiSecret('xyz') %}
```
The api secret is not updated.

Looks like the following is missing from `nystudio107\instantanalyticsGa4\ga4\Analytics::setApiSecret` on (approx) line 262.

```
$service->setApiSecret($apiSecret);
```

Version: 3.0.0-beta.2

**Comment by khalwat** [comment]
So I tried replicating this... here are my plugin settings:

<img width="649" alt="Screenshot 2023-08-13 at 16 23 12" src="https://github.com/nystudio107/craft-instantanalytics-ga4/assets/7570798/802ac4ae-dd06-4ec4-8602-e30e3d3d235e">

...and here's the Twig code:

```twig
    {% do instantAnalytics.setMeasurementId("G-7DDE6SKB8E") %}
    {% do instantAnalytics.setApiSecret('xyz') %}
    {% dd instantAnalytics %}
```

Which outputs:

<img width="517" alt="Screenshot 2023-08-13 at 16 24 42" src="https://github.com/nystudio107/craft-instantanalytics-ga4/assets/7570798/99cb10ea-9e0d-4e4f-9f22-7cba8009c1a9">

...so it is changing both properties. Is there something I'm missing here?

**Comment by mikeymeister** [comment]
I've upgraded to the latest v3 version as I was one behind, just to be sure but am still getting the same results. If I follow your example:

Settings:
![analytics-settings](https://github.com/nystudio107/craft-instantanalytics-ga4/assets/34517288/e4ceba57-0558-4407-bf9e-3cb159e19ed0)

Template:
```
{% do instantAnalytics.setMeasurementId("replacement-key") %}
{% do instantAnalytics.setApiSecret("replacement-secret") %}
{% dd instantAnalytics %}
```
Result:
![analytics-dump](https://github.com/nystudio107/craft-instantanalytics-ga4/assets/34517288/18f50529-3a08-4535-99b2-a5c27b892e27)

My suggestion about the code was just noticing a difference between how the setMeasurementId() and setApiSecret functions were different.

```php
/**
     * Set the measurement id.
     *
     * @param string $measurementId
     * @return $this
     */
    public function setMeasurementId(string $measurementId): self
    {
        $service = $this->service();

        if (!$service) {
            throw new InvalidConfigException('instant-analytics-ga4', 'Unable to create GA4 service object');
        }

        $service->setMeasurementId($measurementId);
        return $this;
    }

    /**
     * Set the API secret.
     *
     * @param string $apiSecret
     * @return $this
     */
    public function setApiSecret(string $apiSecret): self
    {
        $service = $this->service();

        if (!$service) {
            throw new InvalidConfigException('instant-analytics-ga4', 'Unable to create GA4 service object');
        }

        return $this;
    }
```
Maybe I am missing something? Happy to provide any more info, and really appreciate your help with this.

**Comment by khalwat** [comment]
Ah I think this is specific to the v3 version, it's an oversight. Thanks for the report!

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-instantanalytics-ga4/commit/ab4faa9b1da40cc5fa227fd09eef20281a95dd0f
