### ISSUE TITLE
Custom Config

### ISSUE THREAD

**Issue by daniellelecomte** [nystudio107/craft-instantanalytics-ga4#19]
### Question
Should the config file be named `instant-analytics.php` or `instantanalytics.php`? The docs mention one, but the config file to copy and start from is the other. 

Regardless, neither of these are working for me.

### Additional context
Craft 3.9.4
IA 3.0.0-beta.3

**Comment by samuelbirch** [comment]
should be `instant-analytics-ga4.php`

**Comment by khalwat** [comment]
^ yep
