### ISSUE TITLE
Brand field not available

### ISSUE THREAD

**Issue by bossanova808** [nystudio107/craft-instantanalytics-ga4#2]
(Latest of both Craft and this plugin obviously)

My brand field is not available in this list:

![image](https://github.com/nystudio107/craft-instantanalytics-ga4/assets/731309/d8b842c7-8939-471e-bae9-ae2e46abfa82)

It is an Entries field:

![image](https://github.com/nystudio107/craft-instantanalytics-ga4/assets/731309/b01fe6d3-9c3c-4132-884d-e8af14228601)

How is this selection built?  Is it e.g. filtering out fields that are not on ALL product types perhaps?  

In the past I have used code to add the brand, by the looks of thing, but be easier if I could just select the field (and ideally a fallback value if the field is empty or N/A)

**Comment by khalwat** [comment]
Yeah it's a bug, you should be able to select the field. Will get it fixed.

This is what it is doing currently:

```php
        $commerceFields = [];

        if (self::$commercePlugin !== null) {
            $productTypes = self::$commercePlugin->getProductTypes()->getAllProductTypes();

            foreach ($productTypes as $productType) {
                $productFields = $this->getPullFieldsFromLayoutId($productType->fieldLayoutId);
                /** @noinspection SlowArrayOperationsInLoopInspection */
                $commerceFields = array_merge($commerceFields, $productFields);
                if ($productType->hasVariants) {
                    $variantFields = $this->getPullFieldsFromLayoutId($productType->variantFieldLayoutId);
                    /** @noinspection SlowArrayOperationsInLoopInspection */
                    $commerceFields = array_merge($commerceFields, $variantFields);
                }
            }
        }
```

**Comment by bossanova808** [comment]
That seems like it should work...?

**Comment by khalwat** [comment]
Added in 4.0.0-beta.2
