### ISSUE TITLE
Send commerce events aren't being transformed to monetization report

### ISSUE THREAD

**Issue by jripmeester** [nystudio107/craft-instantanalytics-ga4#20]
Instant Analytics is correctly sending events to GA4. Include the commerce events (add_to_cart, purchase, etc). But these events aren't transformed to the monetization report. Probably because some required fields are missing (for example; currency).

### To reproduce
Steps to reproduce the behaviour:
1. Install Instant Analytics GA4 in a Craft 3 with Commerce 3 enviroment
2. Setup the correct GA4 keys to get the events going.
3. Add a product to the cart and complete the order
4. In GA4 you'll sent the events being registered but no records are added to the monetization report

### Expected behaviour
The events that are registered should be included in the Monetization report.

### Links
Here's an overview of the required fields per event
https://developers.google.com/analytics/devguides/collection/ga4/reference/events?client_type=gtag#add_to_cart
Here the notes indicate why the events are not included in the report
https://support.google.com/analytics/answer/12924131?hl=en&ref_topic=13818299&sjid=7744061481099581986-EU

### Versions
- Plugin version: 3.0.0-beta.3
- Craft version: 3.7.66
- Commerce version: 3.4.19

**Comment by janhenckens** [comment]
Came here to report a similar issue. We see events in GA4 but are missing pricing data.
Checked our setup (measurement id, api key) and the other settings are all on automatic.

**Comment by khalwat** [comment]
Addressed in:

Craft 3 -> Version 3.0.0-beta.4: https://github.com/nystudio107/craft-instantanalytics-ga4/releases/tag/3.0.0-beta.4

Craft 4 -> Version 4.0.0-beta.5: https://github.com/nystudio107/craft-instantanalytics-ga4/releases/tag/4.0.0-beta.5

**Comment by jripmeester** [comment]
Updated! Thanks @khalwat!

**Comment by jripmeester** [comment]
@khalwat Sorry to open this one up again. The view_item event isn't being registered in the monetization report either.
The currency value also needs to be added to the addProductDataFromProductOrVariant function. When i add that in the code the event gets handled correctly.

**Comment by khalwat** [comment]
@jripmeester on it

**Comment by khalwat** [comment]
Addressed & released:

Craft 3: https://github.com/nystudio107/craft-instantanalytics-ga4/releases/tag/3.0.0

Craft 4: https://github.com/nystudio107/craft-instantanalytics-ga4/releases/tag/4.0.0
