### ISSUE TITLE
InvalidArgumentException: Event list must not exceed 25 items

### ISSUE THREAD

**Issue by phillmorgan28** [nystudio107/craft-instantanalytics-ga4#24]
### Describe the bug
We're getting an error on our store when a user adds a large number of items to the cart. The error is being thrown inside one of your plugins dependencies but isn't caught by your code.

### To reproduce
Steps to reproduce the behaviour:
1. Add more than 25 items to the cart
2. Receive an internal server error message on the front end
3. Check log and see error "InvalidArgumentException: Event list must not exceed 25 items" coming from "br33f/php-ga4-mp"

### Expected behaviour
The cart should not fail, additional parameters should be truncated to allow the cart to function normally.

### Versions
- Plugin version: 4
- Craft version: 4

**Comment by khalwat** [comment]
Addressed in:

Craft CMS 3.x: Version 3.0.1 -> https://github.com/nystudio107/craft-instantanalytics-ga4/releases/tag/3.0.1

Craft CMS 4.x: Version 4.0.1 -> https://github.com/nystudio107/craft-instantanalytics-ga4/releases/tag/4.0.1
