### ISSUE TITLE
addCommerceProductListImpression requires both arguments

### ISSUE THREAD

**Issue by pixelmachine** [nystudio107/craft-instantanalytics-ga4#25]
The docs state that `addCommerceProductListImpression` has two arguments and the second is optional:

> PAGE_PRODUCTS should be an array of Product or Variant elements, while LIST_NAME should be a name for the product list being displayed. It’s optional and defaults to default if not specified

However when I use it like so:
```js
{% do instantAnalytics.addCommerceProductListImpression(products) %}
```
I get the following error:
```log
Too few arguments to function nystudio107\instantanalyticsGa4\ga4\Analytics::addCommerceProductListImpression(), 
1 passed in /craft3/vendor/twig/twig/src/Extension/CoreExtension.php on line 1570 
and exactly 2 expected in /craft3/vendor/nystudio107/craft-instantanalytics-ga4/src/ga4/Analytics.php at line 230
```

### Versions
- Plugin version: v3.x-dev
- Craft version: 3.9.6

**Comment by khalwat** [comment]
Addressed in:

Craft CMS 3.x: Version 3.0.1 -> https://github.com/nystudio107/craft-instantanalytics-ga4/releases/tag/3.0.1

Craft CMS 4.x: Version 4.0.1 -> https://github.com/nystudio107/craft-instantanalytics-ga4/releases/tag/4.0.1
