### ISSUE TITLE
Page View Question

### ISSUE THREAD

**Issue by codyjames** [nystudio107/craft-instantanalytics-ga4#26]
Hey there!
Quick question: if I'm trying to use Instant Analytics and the gtag snippet, should I be disabling Page Views on one of the two?

Followup question: is GA4 Realtime analytics possible if not collecting pageviews via the gtag snippet?

Let me know.
Thanks!

**Comment by khalwat** [comment]
Yes, you probably only want to send page views from one or the other.

Yes, real-time analytics should be possible without using gtag.

**Comment by codyjames** [comment]
Great, thanks for the info! Realtime isn't working for me for now but I'll wait a few days and see if it start showing up.
