### ISSUE TITLE
Front end error

### ISSUE THREAD

**Issue by georgiaevans** [nystudio107/craft-instantanalytics-ga4#29]
After the latest update of the plugin to 3.0.1, I'm getting an error on the front end of the site. CMS is working fine with no issues, but the following front end:

An Error occurred while handling another error:
ParseError: syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/html/vendor/nystudio107/craft-instantanalytics-ga4/src/ga4/Analytics.php:81

![Screenshot 2024-02-06 at 12 51 58](https://github.com/nystudio107/craft-instantanalytics-ga4/assets/141626569/ccef639f-e7a1-4225-83a7-626b8227baad)

- Plugin version: 3.0.1
- Craft version: 3.9.10

**Comment by khalwat** [comment]
Addressed.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-craft-instantanalytics-ga4": "dev-develop-v3 as 3.0.2”,
```
Then do a `composer clear-cache && composer update`
