### ISSUE TITLE
Don't set cookies until you need to (for cacheability)

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-instantanalytics-ga4#30]
It appears that regardless of configuration, if the plugin is installed, web requests will always end up with a an `_ia` cookie set.
I thought this would be solely controlled with `autoSendPageView`, but that doesn't appear to be the case. 

For example:

```
'autoSendPageView' => false,
'requireGaCookieClientId' => false,
```

A blank template still sends up with a `Set-Cookie: _ia=…`.

A response with a `Set-Cookie: ` header is often used an indicator to caching mechanisms that this response should _not_ be cached. This includes static caches like Craft Cloud, Fastly, Varnish, Cloudflare.

In my example, IA is only being used for the Commerce event integration, but having the plugin enabled disabled static cache globally.

**Comment by khalwat** [comment]
Have you tried using the `createGclidCookie` setting and setting it to `false`?

This will not cause IA to use the cookie and, instead, rely on ga4 cookie.

**Comment by timkelty** [comment]
That seems to work!
