### ISSUE TITLE
Allow accessing BaseRequest object

### ISSUE THREAD

**Issue by JeroenJRP** [nystudio107/craft-instantanalytics-ga4#31]
Hi, we're in as situation where the client wants us to send the timestamp with the GMP event. 
The `br33f/php-ga4-mp` library allows doing this with `$baseRequest->setTimestampMicros($timestamp);`, but the problem i'm running into is that this plugin doesn't allow access to the BaseRequest object.
So my request is to change the visibilty of the `request()` method in `ga4/Analytics.php` from `protected` to `public` to allow setting extra properties on the BaseRequest when needed.

**Comment by khalwat** [comment]
Sounds reasonable to me!

**Comment by khalwat** [comment]
Addressed in the above commits

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-instantanalytics-ga4": "dev-develop as 3.0.2”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-instantanalytics-ga4": "dev-develop-v4 as 4.0.2”,
```
Then do a `composer clear-cache && composer update`
