### ISSUE TITLE
Craft 5 Support

### ISSUE THREAD

**Issue by joelzerner** [nystudio107/craft-instantanalytics-ga4#32]
Thanks for your great work on this plugin!
Just checking to see if it will be ported to Craft 5 and if so, what the timing is?

**Comment by khalwat** [comment]
Yep, it will be ported!

**Comment by khalwat** [comment]
Now available for Craft 5 -> https://plugins.craftcms.com/instant-analytics-ga4?craft5=

**Comment by joelzerner** [comment]
Amazing - thank you!
