### ISSUE TITLE
Variable "instantAnalytics" does not exist error

### ISSUE THREAD

**Issue by green17** [nystudio107/craft-instantanalytics-ga4#33]
### Question
We are currently running Instant Analytics GA4 on trial but are unable to get it to pass events to GA4. We have a measurement key and secret set up which we have tested sucessfully on a separate install, we have also tested other key/secret combinations on the new install but to no avail. We don't send page views as we collect these separately, though we have also tested by removing all other GA4/Tag Manager code and switched page view tracking on. In testing for the instantAnalytics object we get this from our base layout template: 

{% dd instantAnalytics %}

nystudio107\instantanalyticsGa4\ga4\Analytics {#2689 ▼
  -_request: Br33f\Ga4\MeasurementProtocol\Dto\Request\BaseRequest {#2700 ▶}
  -_service: nystudio107\instantanalyticsGa4\ga4\Service {#2688 ▶}
  -_affiliation: null
  -_shouldSendAnalytics: null
  -_sessionString: null
  -eventList: []
}

On other templates, which extend the base template, we get this error: Variable "instantAnalytics" does not exist.

Creating events like in the sample below results in the same error.
 {# @var viewItemEvent \Br33f\Ga4\MeasurementProtocol\Dto\Event\ViewItemEvent #}
 {% set viewItemEvent = instantAnalytics.create.ViewItemEvent %}
 {% do viewItemEvent.setValue(51.10).setCurrency('EUR') %}

### Additional context
Craft Pro 4.8.6
Craft Commerce 4.5.2
Instant Analytics GA4 4.0.2

**Comment by khalwat** [comment]
So you had it working in one project, but it's not working in a new project?

I'd look for differences between the two projects... but offhand, I don't know how or why the `instantAnalytics` variable wouldn't be available, it's added here:

https://github.com/nystudio107/craft-instantanalytics-ga4/blob/develop-v4/src/InstantAnalytics.php#L249

**Comment by green17** [comment]
@khalwat I'm not sure what went wrong exactly, but an uninstall/re-install resolved the issue.
