### ISSUE TITLE
Is Gtag supported?

### ISSUE THREAD

**Issue by tibbis** [nystudio107/craft-instantanalytics-ga4#34]
### Question
Hi! I’m using GA4 with GTM to manage some tags for link button clicks. To improve speed I would like to test out this plugin but not sure it supports gtag/js?

**Comment by khalwat** [comment]
So... this plugin is largely a _replacement_ for gtag/js, though it can be used in conjunction with it if you take some caveats into account:

https://nystudio107.com/docs/instant-analytics-ga4/configuring.html#configuring-instant-analytics-ga4

> NOTE: Instant Analytics GA4 will work with the traditional Google Analytics Tracking Code JavaScript tag; it’s not an either/or, they can coexist. Instant Analytics GA4 is just a different way to send the same data to Google Analytics.
