### ISSUE TITLE
Instant Analytics requires SEOmatic

### ISSUE THREAD

**Issue by jdsdev** [nystudio107/craft-instantanalytics-ga4#35]
### Describe the bug
Instant Analytics requires SEOmatic for some of its functionality, but SEOmatic is not a required dependency. Ideally the two could function as standalone plugins

### To reproduce
Steps to reproduce the behaviour:
1. Install `nystudio107/craft-instantanalytics-ga4` but not `nystudio107/craft-seomatic`.
2. Create an `{{ eventTrackingUrl(URL, EVENT_NAME, PARAMS) }}.`
3. Click the link: `Class "nystudio107\seomatic\helpers\Json" not found`

### Versions
- Plugin version: 5.0.0
- Craft version: 5.4.3

**Comment by khalwat** [comment]
Ah yes, this is definitely a bug.

**Comment by khalwat** [comment]
Released as 5.0.1 -> https://github.com/nystudio107/craft-instantanalytics-ga4/releases/tag/5.0.1
