### ISSUE TITLE
Licenses and Craft 3 Support

### ISSUE THREAD

**Issue by smockensturm** [nystudio107/craft-instantanalytics-ga4#8]
Hi @khalwat

Do licenses transfer?

On a scale of 1-10, what is your sense of obligation for making this new plugin Craft 3 / Commerce 3 compatible until end-of-life? (April 30, 2024)

Because this puts us in a little pickle as we were not quite prepared, nor have the budget, to do those major upgrades right this second.

Or perhaps you can give us a sense of what that would take and we can either a) fork it or b) pay you handsomely. What? Half a days work? More?

Thanks for everything.

**Comment by khalwat** [comment]
I'm open to the idea of backporting it to Craft 3, that's actually on the roadmap (with a ?). I was waiting to see if there was a demand for such a thing.

As for licenses transferring, given that we had to rewrite pretty much everything, it seemed appropriate to make it a separate plugin with a separate license.

**Comment by smockensturm** [comment]
> I'm open to the idea of backporting it to Craft 3, that's actually on the roadmap (with a ?). I was waiting to see if there was a demand for such a thing.

Great. +1 toward said demand.

> As for licenses transferring, given that we had to rewrite pretty much everything, it seemed appropriate to make it a separate plugin with a separate license.

Of course.

**Comment by CharlieGentle** [comment]
+1 to Craft 3 version

**Comment by bymayo** [comment]
+1 for Craft 3 version (Urgently 😂)

We've got many clients using Craft 3 / Commerce 3 + GA, that can't update to Craft 4 / Commerce 4 yet due to other complexities (Adjusters, Third Party API's etc)

**Comment by khalwat** [comment]
Craft 3 version has been released:

https://github.com/nystudio107/craft-instantanalytics-ga4/releases/tag/3.0.0-beta.1

**Comment by bymayo** [comment]
@khalwat Amazing! Thanks for sorting that so fast! 🎉🎉🎉🎉

**Comment by bymayo** [comment]
@khalwat I don't know whether to post this as a seperate issue or not, but we're getting an error with `parseEnv()` on lines 315 and 316 in `../vendor/nystudio107/craft-instantanalytics-ga4/src/ga4/Analytics.php` using Craft 3.6.18.

Looks like it needs to be `Craft::parseEnv` not `App::parseEnv`

**Comment by khalwat** [comment]
Yeah if you could post it as a new issue, that'd be great.
